#pragma once

#include "Shushao/Application.h"
#include "Shushao/Debug.h"
#include "Shushao/SceneManager.h"
#include "Shushao/Transform.h"
#include "Shushao/ParticleSystem.h"
#include "Shushao/Factory.h"
#include "Shushao/Program.h"
#include "Shushao/MeshRenderer.h"
#include "Shushao/SpriteRenderer.h"
#include "Shushao/Animation.h"
#include "Shushao/Resources.h"
#include "Shushao/Audio.h"
#include "Shushao/GeometryRenderer.h"
#include "Shushao/Font.h"
#include "Shushao/Coroutine.h"
#include "Shushao/Textfile.h"
//#include "Shushao/Shaders/Shader.h"
#include "Shushao/Image.h"

#include "Shushao/UI/CanvasUI.h"
#include "Shushao/UI/TextUI.h"
#include "Shushao/UI/ImageUI.h"

#include "Shushao/Physics/Collider2d.h"
#include "Shushao/Physics/RigidBody2d.h"
#include "Shushao/Physics/Collision2d.h"